use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum NodeConcept {
    DayCanchi,
    MonthCanchi,
    YearCanchi,
    SolarTerm,
    HourCanchi,
    Truc,
    DayDeity,
    NaAm,
    Star,
    Element,
    Direction,
    PersonalAlignment,
    InteractionSignal,
    Recommendation,
    Taboo,
    ChartPillar,
    AxisSignal,
    XungHop,
    HoangDaoHour,
    DayPersonMatrix,
    PersonalHourMatrix,
    ElementResonanceMatrix,
    DirectionMergeMatrix,
    DomainDayBoostMatrix,
    InteractionRow,
    TenGodRelation,
    BranchRelationNode,
    ElementRelationNode,
    DirectionSignalNode,
    HourSlot,
    Activity,
    RecommendationHit,
    RecommendationLayer,
    RecommendationSummary,
}

impl NodeConcept {
    pub fn label(&self) -> ConceptLabel {
        match self {
            Self::DayCanchi => ConceptLabel::DayCanchi,
            Self::MonthCanchi => ConceptLabel::MonthCanchi,
            Self::YearCanchi => ConceptLabel::YearCanchi,
            Self::SolarTerm => ConceptLabel::SolarTerm,
            Self::HourCanchi => ConceptLabel::HourCanchi,
            Self::Truc => ConceptLabel::Truc,
            Self::DayDeity => ConceptLabel::DayDeity,
            Self::NaAm => ConceptLabel::NaAm,
            Self::Star => ConceptLabel::Star,
            Self::Element => ConceptLabel::Element,
            Self::Direction => ConceptLabel::Direction,
            Self::PersonalAlignment => ConceptLabel::PersonalAlignment,
            Self::InteractionSignal => ConceptLabel::InteractionSignal,
            Self::Recommendation => ConceptLabel::Recommendation,
            Self::Taboo => ConceptLabel::Taboo,
            Self::ChartPillar => ConceptLabel::ChartPillar,
            Self::AxisSignal => ConceptLabel::AxisSignal,
            Self::XungHop => ConceptLabel::XungHop,
            Self::HoangDaoHour => ConceptLabel::HoangDaoHour,
            Self::DayPersonMatrix => ConceptLabel::DayPersonMatrix,
            Self::PersonalHourMatrix => ConceptLabel::PersonalHourMatrix,
            Self::ElementResonanceMatrix => ConceptLabel::ElementResonanceMatrix,
            Self::DirectionMergeMatrix => ConceptLabel::DirectionMergeMatrix,
            Self::DomainDayBoostMatrix => ConceptLabel::DomainDayBoostMatrix,
            Self::InteractionRow => ConceptLabel::InteractionRow,
            Self::TenGodRelation => ConceptLabel::TenGodRelation,
            Self::BranchRelationNode => ConceptLabel::BranchRelationNode,
            Self::ElementRelationNode => ConceptLabel::ElementRelationNode,
            Self::DirectionSignalNode => ConceptLabel::DirectionSignalNode,
            Self::HourSlot => ConceptLabel::HourSlot,
            Self::Activity => ConceptLabel::Activity,
            Self::RecommendationHit => ConceptLabel::RecommendationHit,
            Self::RecommendationLayer => ConceptLabel::RecommendationLayer,
            Self::RecommendationSummary => ConceptLabel::RecommendationSummary,
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum EdgeConcept {
    Resonates,
    Conflicts,
    Conditions,
    Supports,
    Weakens,
    Overrides,
    Composes,
    Projects,
    Derives,
    HasMatrix,
    HasRow,
    RelatesTo,
    Evaluates,
    InteractsWith,
    HasTenGodRelation,
    HasBranchRelation,
    HasElementRelation,
    BestFor,
    Recommends,
    AdvisesAgainst,
    ContributesTo,
    OriginatesFrom,
    TargetsActivity,
    ProducedByLayer,
    Aggregates,
}

impl EdgeConcept {
    pub fn label(&self) -> ConceptLabel {
        match self {
            Self::Resonates => ConceptLabel::Resonates,
            Self::Conflicts => ConceptLabel::Conflicts,
            Self::Conditions => ConceptLabel::Conditions,
            Self::Supports => ConceptLabel::Supports,
            Self::Weakens => ConceptLabel::Weakens,
            Self::Overrides => ConceptLabel::Overrides,
            Self::Composes => ConceptLabel::Composes,
            Self::Projects => ConceptLabel::Projects,
            Self::Derives => ConceptLabel::Derives,
            Self::HasMatrix => ConceptLabel::HasMatrix,
            Self::HasRow => ConceptLabel::HasRow,
            Self::RelatesTo => ConceptLabel::RelatesTo,
            Self::Evaluates => ConceptLabel::Evaluates,
            Self::InteractsWith => ConceptLabel::InteractsWith,
            Self::HasTenGodRelation => ConceptLabel::HasTenGodRelation,
            Self::HasBranchRelation => ConceptLabel::HasBranchRelation,
            Self::HasElementRelation => ConceptLabel::HasElementRelation,
            Self::BestFor => ConceptLabel::BestFor,
            Self::Recommends => ConceptLabel::Recommends,
            Self::AdvisesAgainst => ConceptLabel::AdvisesAgainst,
            Self::ContributesTo => ConceptLabel::ContributesTo,
            Self::OriginatesFrom => ConceptLabel::OriginatesFrom,
            Self::TargetsActivity => ConceptLabel::TargetsActivity,
            Self::ProducedByLayer => ConceptLabel::ProducedByLayer,
            Self::Aggregates => ConceptLabel::Aggregates,
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum ConceptLabel {
    DayCanchi,
    MonthCanchi,
    YearCanchi,
    SolarTerm,
    HourCanchi,
    Truc,
    DayDeity,
    NaAm,
    Star,
    Element,
    Direction,
    PersonalAlignment,
    InteractionSignal,
    Recommendation,
    Taboo,
    ChartPillar,
    AxisSignal,
    XungHop,
    HoangDaoHour,
    DayPersonMatrix,
    PersonalHourMatrix,
    ElementResonanceMatrix,
    DirectionMergeMatrix,
    DomainDayBoostMatrix,
    InteractionRow,
    TenGodRelation,
    BranchRelationNode,
    ElementRelationNode,
    DirectionSignalNode,
    HourSlot,
    Activity,
    RecommendationHit,
    RecommendationLayer,
    RecommendationSummary,
    Resonates,
    Conflicts,
    Conditions,
    Supports,
    Weakens,
    Overrides,
    Composes,
    Projects,
    Derives,
    HasMatrix,
    HasRow,
    RelatesTo,
    Evaluates,
    InteractsWith,
    HasTenGodRelation,
    HasBranchRelation,
    HasElementRelation,
    BestFor,
    Recommends,
    AdvisesAgainst,
    ContributesTo,
    OriginatesFrom,
    TargetsActivity,
    ProducedByLayer,
    Aggregates,
}

impl ConceptLabel {
    pub fn as_str(&self) -> &'static str {
        match self {
            Self::DayCanchi => "day_canchi",
            Self::MonthCanchi => "month_canchi",
            Self::YearCanchi => "year_canchi",
            Self::SolarTerm => "solar_term",
            Self::HourCanchi => "hour_canchi",
            Self::Truc => "truc",
            Self::DayDeity => "day_deity",
            Self::NaAm => "na_am",
            Self::Star => "star",
            Self::Element => "element",
            Self::Direction => "direction",
            Self::PersonalAlignment => "personal_alignment",
            Self::InteractionSignal => "interaction_signal",
            Self::Recommendation => "recommendation",
            Self::Taboo => "taboo",
            Self::ChartPillar => "chart_pillar",
            Self::AxisSignal => "axis_signal",
            Self::XungHop => "xung_hop",
            Self::HoangDaoHour => "hoang_dao_hour",
            Self::DayPersonMatrix => "day_person_matrix",
            Self::PersonalHourMatrix => "personal_hour_matrix",
            Self::ElementResonanceMatrix => "element_resonance_matrix",
            Self::DirectionMergeMatrix => "direction_merge_matrix",
            Self::DomainDayBoostMatrix => "domain_day_boost_matrix",
            Self::InteractionRow => "interaction_row",
            Self::TenGodRelation => "ten_god_relation",
            Self::BranchRelationNode => "branch_relation_node",
            Self::ElementRelationNode => "element_relation_node",
            Self::DirectionSignalNode => "direction_signal_node",
            Self::HourSlot => "hour_slot",
            Self::Activity => "activity",
            Self::RecommendationHit => "recommendation_hit",
            Self::RecommendationLayer => "recommendation_layer",
            Self::RecommendationSummary => "recommendation_summary",
            Self::Resonates => "resonates",
            Self::Conflicts => "conflicts",
            Self::Conditions => "conditions",
            Self::Supports => "supports",
            Self::Weakens => "weakens",
            Self::Overrides => "overrides",
            Self::Composes => "composes",
            Self::Projects => "projects",
            Self::Derives => "derives",
            Self::HasMatrix => "has_matrix",
            Self::HasRow => "has_row",
            Self::RelatesTo => "relates_to",
            Self::Evaluates => "evaluates",
            Self::InteractsWith => "interacts_with",
            Self::HasTenGodRelation => "has_ten_god_relation",
            Self::HasBranchRelation => "has_branch_relation",
            Self::HasElementRelation => "has_element_relation",
            Self::BestFor => "best_for",
            Self::Recommends => "recommends",
            Self::AdvisesAgainst => "advises_against",
            Self::ContributesTo => "contributes_to",
            Self::OriginatesFrom => "originates_from",
            Self::TargetsActivity => "targets_activity",
            Self::ProducedByLayer => "produced_by_layer",
            Self::Aggregates => "aggregates",
        }
    }
}

pub struct GraphOntology;

impl GraphOntology {
    pub fn node_concepts() -> &'static [NodeConcept] {
        &[
            NodeConcept::DayCanchi,
            NodeConcept::MonthCanchi,
            NodeConcept::YearCanchi,
            NodeConcept::SolarTerm,
            NodeConcept::HourCanchi,
            NodeConcept::Truc,
            NodeConcept::DayDeity,
            NodeConcept::NaAm,
            NodeConcept::Star,
            NodeConcept::Element,
            NodeConcept::Direction,
            NodeConcept::PersonalAlignment,
            NodeConcept::InteractionSignal,
            NodeConcept::Recommendation,
            NodeConcept::Taboo,
            NodeConcept::ChartPillar,
            NodeConcept::AxisSignal,
            NodeConcept::XungHop,
            NodeConcept::HoangDaoHour,
            NodeConcept::DayPersonMatrix,
            NodeConcept::PersonalHourMatrix,
            NodeConcept::ElementResonanceMatrix,
            NodeConcept::DirectionMergeMatrix,
            NodeConcept::DomainDayBoostMatrix,
            NodeConcept::InteractionRow,
            NodeConcept::TenGodRelation,
            NodeConcept::BranchRelationNode,
            NodeConcept::ElementRelationNode,
            NodeConcept::DirectionSignalNode,
            NodeConcept::HourSlot,
            NodeConcept::Activity,
            NodeConcept::RecommendationHit,
            NodeConcept::RecommendationLayer,
            NodeConcept::RecommendationSummary,
        ]
    }

    pub fn edge_concepts() -> &'static [EdgeConcept] {
        &[
            EdgeConcept::Resonates,
            EdgeConcept::Conflicts,
            EdgeConcept::Conditions,
            EdgeConcept::Supports,
            EdgeConcept::Weakens,
            EdgeConcept::Overrides,
            EdgeConcept::Composes,
            EdgeConcept::Projects,
            EdgeConcept::Derives,
            EdgeConcept::HasMatrix,
            EdgeConcept::HasRow,
            EdgeConcept::RelatesTo,
            EdgeConcept::Evaluates,
            EdgeConcept::InteractsWith,
            EdgeConcept::HasTenGodRelation,
            EdgeConcept::HasBranchRelation,
            EdgeConcept::HasElementRelation,
            EdgeConcept::BestFor,
            EdgeConcept::Recommends,
            EdgeConcept::AdvisesAgainst,
            EdgeConcept::ContributesTo,
            EdgeConcept::OriginatesFrom,
            EdgeConcept::TargetsActivity,
            EdgeConcept::ProducedByLayer,
            EdgeConcept::Aggregates,
        ]
    }
}
